baseURL: https://loyaltypipe.com/
languageCode: en-us
title: Loyalty Pipe
theme: hugo-fresh
googleAnalytics: UA-150569709-1 #Put in your tracking code without quotes like this: UA-XXXXXX...
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy 
  description: Foster community around your brand
  # navbarlogo:
  # # Logo (from static/images/logos/___)
  #  image: logos/fresh.svg
  #  link: /
  font:
    name: "Forecaster Work Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Loyalty Pipe
    # Hero subtitle (optional)
    subtitle: Foster community around your brand through understanding your product consumers.
    # Button text
    buttontext: Learn more
    # Where the main hero button links to
    buttonlink: "mission/index.html"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  # navbar:
  # - title: Features
  #   url: /
  # - title: Pricing
  #   url: /
  # - title: Case Studies
  #   sublinks:
  #   - title: Fashion Boutiques in NYC
  #     url: /
  #   - title: Expanding product companies
  #     url: /
  #   - title: Internal product testing
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  # section1:
  #   title: Great power comes
  #   subtitle: with great responsibility
  #   tiles:
  #   - title: Feedback
  #     icon: laptop-cloud
  #     text: Equip your customers to share their feedback 
  #     # url: /
  #     # buttonText: Free trial
  #   - title: Cloud integration
  #     icon: mouse-globe
  #     text: Collectable stats for your existing tools
  #     # url: /
  #     # buttonText: Get started
  #   - title: Use your preferred tools
  #     icon: plug-cloud
  #     text: Automatic integrations with existing infrastructure
  #     # url: /
  #     # buttonText: Get started
  # section2:
  #   title: You're here because you want the best
  #   subtitle: And we know it
  #   features:
  #   - title: Powerful and unified interface
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     # Icon (from /images/illustrations/icons/___.svg)
  #     icon: laptop-globe
  #   - title: Cross-device synchronisation
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: doc-sync
  #   - title: Nomad system
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: mobile-feed
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  section5: true
  # footer:
  #   # Logo (from /images/logos/___)
  #   logo: fresh-white-alt.svg
  #   # Social Media Title
  #   socialmediatitle: Follow Us
  #   # Social media links (GitHub, Twitter, etc.). All are optional.
  #   socialmedia:
  #   - link: https://github.com/lucperkins/github-fresh
  #     # Icons are from Font Awesome
  #     icon: github
  #   - link: https://dribbble.com/#
  #     icon: dribbble
  #   - link: https://facebook.com/#
  #     icon: facebook
  #   - link: https://twitter.com/lucperkins
  #     icon: twitter
  #   - link: https://bitbucket.org/#
  #     icon: bitbucket
  #   bulmalogo: true
  #   quicklinks:
  #     column1:
  #       title: "Product"
  #       links:
  #       - text: Discover features
  #         link: /
  #       - text: Why choose our product?
  #         link: /
  #       - text: Compare features
  #         link: /
  #       - text: Our roadmap
  #         link: /
  #       - text: AGB
  #         link: /agb
  #     column2:
  #       title: "Docs"
  #       links:
  #       - text: Get started
  #         link: /
  #       - text: User guides
  #         link: /
  #       - text: Admin guide
  #         link: /
  #       - text: Developers
  #         link: /
  #     column3:
  #       title: "Blog"
  #       links:
  #       - text: Latest news
  #         link: /blog/first
  #       - text: Tech articles
  #         link: /blog/second
deployment:
  targets:
    name: "s3-landing-page"
    URL: "s3://caster-web?region=us-east-1"
    cloudFrontDistributionID: "912236762686:distribution/E3JJKNWJ5T62RZ"